repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: pnpm run format-check
        language: system
        stages: [pre-commit, pre-push]

  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: pnpm run lint
        pass_filenames: false
        language: system
        stages: [pre-commit, pre-push]

  - repo: local
    hooks:
      - id: test
        name: test
        entry: pnpm run test
        language: system
        stages: [pre-push]

  - repo: local
    hooks:
      - id: tsc
        name: tsc
        entry: pnpm run type-check
        pass_filenames: false
        language: system
        stages: [pre-commit, pre-push]
